### ISSUE TITLE
Feature/How-To: Synchronous Tests w/Fail-Only Output

### ISSUE THREAD

**Issue by tooolbox** [tapjs/tapjs#166]
I'm currently writing a number of file-processing scripts, and I wanted to do some assertions on the state of the files before and after.  I'm using Chai for this, which is fine; my script simply dies if an assertion fails.

However, I'd like to make the assertions a little more descriptive.  I like the idea of using Tap, Mocha-style, with `describe()` and `it()`!  However, there's two problems/issues:
- Tap seems to only run after my script has otherwise finished, whereas I'd like to run tests before, after, and in the middle of my processing routine.  (I'm guessing it's hooked onto the process end, but it's not obvious from the code.)  So some sort of synchronous method of running would be sweet.
- I'd like to have Tap only output the reporter contents if a test fails.  So my script just runs, but if something goes wrong I get a big report about what went wrong and why.

My concept would be doing something like this:

``` js
var fs = require('fs');
var should = require('chai').should();
var tap = require('tap');

tap.mochaGlobals();

var fileContent = fs.readFileSync('./testFile.txt');
describe('the file when we start', function(){
    it('should have content', function(){
        fileContent.should.exist;
    });
});

// process the file in some way

describe('the file when we end', function(){
    it('should be changed in some way', function(){
        fileContent.should.contain('new stuff string!');
    });
});

fs.writeFileSync(fileContent, './changedFile.txt');
```

_(Inline diff reporting on failure is also something I'd like to have, but I'm pretty sure that's possible with the various reporters that can be hooked into Tap.)_

I'm wondering if this is possible already and I just didn't realize it (maybe I'm using the API incorrectly--possibly I need to use `.end()` somewhere?), or if it could be added.  I'm open to doing the work to add it if it seems within reason--I would need to be pointed in the right direction.

Thanks!

**Comment by isaacs** [comment]
This works for me:

``` javascript
var fs = require('fs');
var should = require('chai').should();
var tap = require('./');

tap.mochaGlobals();

var fileContent = fs.readFileSync('./testFile.txt', 'utf8');
describe('the file when we start', function(){
    it('should have content', function(){
        fileContent.should.exist;
    });
});

// process the file in some way
fileContent += 'new stuff string!'

describe('the file when we end', function(){
    it('should be changed in some way', function(){
        fileContent.should.contain('new stuff string!');
    });
});

fs.writeFileSync(fileContent, './changedFile.txt');
```

``` tap
TAP version 13
    # Subtest: the file when we start
    ok 1 - should have content
    1..1
ok 1 - the file when we start # time=9.253ms

    # Subtest: the file when we end
    ok 1 - should be changed in some way
    1..1
ok 2 - the file when we end # time=8.511ms

1..2
# time=37.398ms
```

**Comment by isaacs** [comment]
When you run the file with the tap bin, you get this by default:

```
$ tap m.js
m.js .................................................. 2/2
total ................................................. 2/2

  2 passing (181.505ms)

  ok
```

If there's a failure, you get something like this:

```
$ tap m.js
m.js .................................................. 1/2
  the file when we end
  not ok should be changed in some way
    at:
      file: m.js
      line: 19
      column: 28
    showDiff: false
    actual: |-
      ok
      old junk string!
    expected: null
    message: "AssertionError: expected 'ok\\nold junk string!' to include 'new stuff string!'"
    source: |
      fileContent.should.contain('new stuff string!');
    stack: |
      m.js:19:28
      Test.<anonymous> (lib/assert.js:235:7)
      Test.ASSERT [as _currentAssert] (lib/test.js:1080:15)
      it (lib/mocha.js:28:7)
      m.js:18:5
      lib/mocha.js:45:7
      Test.test (lib/test.js:404:27)
      describe (lib/mocha.js:44:7)

total ................................................. 1/2


  1 passing (198.216ms)
  1 failing
```

**Comment by isaacs** [comment]
If you want less output, you can use `-Rmin` to be completely silent unless there's a failure.  (It also does a clear-screen, which I'm not a huge fan of, but whatever.)

> Tap seems to only run after my script has otherwise finished, whereas I'd like to run tests before, after, and in the middle of my processing routine. (I'm guessing it's hooked onto the process end, but it's not obvious from the code.) So some sort of synchronous method of running would be sweet.

This is confusing to me.  Tap runs synchronously, so yeah, the first test runs, then the processing runs, then the second test runs.  Do you have an example where that's not happening?

**Comment by tooolbox** [comment]
Thanks for the tip on the -Rmin flag.  I guess that's not in tap, but in the reporter(s)?  Couldn't find anything like that in your source code.

> This is confusing to me. Tap runs synchronously, so yeah, the first test runs, then the processing runs, then the second test runs. Do you have an example where that's not happening?

Sure:

``` js
var fs = require('fs');
var should = require('chai').should();
var tap = require('tap');

tap.mochaGlobals();
tap._bail = true;

var fileContent = fs.readFileSync('./names.txt', 'utf8');
console.log('Initial content:\n');
console.log(fileContent);
describe('the file when we start', function(){
    it('should have content', function(){
        fileContent.should.equal('Ana\nBenjamin\nFrank\n');
    });
});

// process the file in some way
console.log('Adding Lara...');
fileContent += 'Lara\n'

describe('the file when we end', function(){
    it("should now have Lara's name", function(){
        fileContent.should.contain('Lara');
    });
});

console.log('Adding Joe...');
fileContent += 'Joe\n';

// Failing test!
describe('the file when we end', function(){
    it("should now have Bob's name", function(){
        fileContent.should.contain('Bob');
    });
});

console.log('Adding Bob...');
fileContent += 'Bob\n';

describe('the file when we end', function(){
    it("should now have Bob's name", function(){
        fileContent.should.contain('Bob');
    });
});

console.log('Writing file...');
fs.writeFileSync('./changedFile.txt', fileContent);

console.log('Done!');
```

This produces the output:

``` bash
Initial content:

Ana
Benjamin
Frank

Adding Lara...
Adding Joe...
Adding Bob...
Writing file...
Done!
TAP version 13
    # Subtest: the file when we start
    ok 1 - should have content
    1..1
ok 1 - the file when we start # time=9.972ms

    # Subtest: the file when we end
    ok 1 - should now have Lara's name
    1..1
ok 2 - the file when we end # time=5.596ms

    # Subtest: the file when we end
    not ok 1 - should now have Bob's name
      ---
      at:
        file: test_tap.js
        line: 32
        column: 28
      showDiff: false
      actual: |
        Ana
        Benjamin
        Frank
        Lara
        Joe
      expected: null
      message: "AssertionError: expected 'Ana\\nBenjamin\\nFrank\\nLara\\nJoe\\n' to include 'Bob'"
      source: |
        fileContent.should.contain('Bob');
      stack: |
        test_tap.js:32:28
        Test.<anonymous> (node_modules/tap/lib/assert.js:235:7)
        Test.ASSERT [as _currentAssert] (node_modules/tap/lib/test.js:1080:15)
        it (node_modules/tap/lib/mocha.js:28:7)
        test_tap.js:31:5
        node_modules/tap/lib/mocha.js:45:7
        Test.test (node_modules/tap/lib/test.js:404:27)
        describe (node_modules/tap/lib/mocha.js:44:7)
        Object.<anonymous> (test_tap.js:30:1)
      ...
    Bail out! # should now have Bob's name
Bail out! # should now have Bob's name
```

The behavior I'm trying to create is, after the 2nd test where 'Joe' is added to the string, and yet 'Bob' is looked for, would be to get Tap to give its report and have my script stop.  What seems to be happening is that the script ends fully (including writing the completed file to disk) before Tap does anything.

Although, you're right, the tests do seem to operate synchronously...  Maybe it's simply that Tap isn't throwing an exception when it bails, so the script rolls on, and then the reporter is outputting asynchronously?

Hope this clarifies my thought process a little.

**Comment by rmg** [comment]
For the ordering you want you would need to put the file modifications in their own describe blocks.

**Comment by isaacs** [comment]
I see, so if I understand you correctly, the request is that tap exit the process when it bails out?

That seems like a reasonable request, but it is a change.  The hazard would be if someone has clean-up code or something, but since a bailout already prevents it from running any more child tests, most of the time that means it bails out of any cleanup anyway.

In the short term, you can do this:

``` javascript
tap.on('bailout', function () {
  process.exit(1)
})
```

or as @rmg suggested, put the modification bits in their own test blocks.

**Comment by isaacs** [comment]
@tooolbox If exiting abruptly on bailout solves your issue, then I'd like to close this in favor of #167, so we can re-focus the discussion.  If I'm missing the point of your request, please let me know by posting a comment here, and I'll gladly reopen this :)

**Comment by tooolbox** [comment]
@isaacs I tried that bit of code you gave me, and it does actually interrupt my main script and work fine.  But then, you don't get any kind of a report from Tap...  I tried doing a `throw new Error(...)` but that didn't do anything at all, probably due to some async stuff going on.

It sounds like you _don't_ want to exit the process on bailout, because you lose the test report and thus the point of the tests.  Is there a happy medium?

Thanks for your attention on this!  :)

@rmg Hm.  I don't know that sticking every single piece of code I have into a `describe()` block is the way I want to go.  

Maybe if, like in Mocha, you could wrap your whole script into a `describe()` block (or `context()` block) that might be workable.  Something along the lines of wrapping your whole script in a [synchronize](http://alexeypetrushin.github.io/synchronize/docs/index.html) fiber to use async functions as synchronous (as I have had to do at least once).

I tried that, though, and it didn't work.  It could be that Tap's BDD syntax just isn't set up for nested describes--the readme does say it's experimental.

For the record, what I tried was this:

``` js
var fs = require('fs');
var should = require('chai').should();
var tap = require('tap');

tap.mochaGlobals();
tap._bail = true;

describe('the whole script', function(){

    var fileContent = fs.readFileSync('./names.txt', 'utf8');
    console.log('Initial content:\n');
    console.log(fileContent);
    describe('the file when we start', function(){
        it('should have content', function(){
            fileContent.should.equal('Ana\nBenjamin\nFrank\n');
        });
    });

    // process the file in some way
    console.log('Adding Lara...');
    fileContent += 'Lara\n'

    describe('the file when we end', function(){
        it("should now have Lara's name", function(){
            fileContent.should.contain('Lara');
        });
    });

    console.log('Adding Joe...');
    fileContent += 'Joe\n';

    // Failing test!
    describe('the file when we end', function(){
        it("should now have Bob's name", function(){
            fileContent.should.contain('Bob');
        });
    });

    console.log('Adding Bob...');
    fileContent += 'Bob\n';

    describe('the file when we end', function(){
        it("should now have Bob's name", function(){
            fileContent.should.contain('Bob');
        });
    });

    console.log('Writing file...');
    fs.writeFileSync('./changedFile.txt', fileContent);

    console.log('Done!');

});
```

And the output was this:

```
Initial content:

Ana
Benjamin
Frank

Adding Lara...
Adding Joe...
Adding Bob...
Writing file...
Done!
TAP version 13
    # Subtest: the whole script
        # Subtest: the file when we start
        ok 1 - should have content
        1..1
    ok 1 - the file when we start # time=4.885ms

        # Subtest: the file when we end
        ok 1 - should now have Lara's name
        1..1
    ok 2 - the file when we end # time=10.574ms

        # Subtest: the file when we end
        not ok 1 - should now have Bob's name
          ---
          at:
            file: test_tap.js
            line: 35
            column: 32
          showDiff: false
          actual: |
            Ana
            Benjamin
            Frank
            Lara
            Joe
          expected: null
          message: "AssertionError: expected 'Ana\\nBenjamin\\nFrank\\nLara\\nJoe\\n' to include 'Bob'"
          source: |
            fileContent.should.contain('Bob');
          stack: |
            test_tap.js:35:32
            Test.<anonymous> (node_modules/tap/lib/assert.js:235:7)
            Test.ASSERT [as _currentAssert] (node_modules/tap/lib/test.js:1080:15)
            it (node_modules/tap/lib/mocha.js:28:7)
            test_tap.js:34:9
            node_modules/tap/lib/mocha.js:45:7
            Test.test (node_modules/tap/lib/test.js:404:27)
            describe (node_modules/tap/lib/mocha.js:44:7)
            test_tap.js:33:5
          ...
        Bail out! # should now have Bob's name
Bail out! # should now have Bob's name
```

So I suppose it didn't bail out of the outer describe block as I had hoped.

**Comment by isaacs** [comment]
@tooolbox What version of Node are you using?  I wonder if this is a streams2/3 issue.

It might be worth pulling in the latest and greatest readable-stream implementation on any 0.x node.

**Comment by isaacs** [comment]
Yep, confirmed this is yet another reason to just use readable-stream v2.  That much at least is fixed on 89ae5e672e4619cfad9bebd11225feefdf85fdde.

**Comment by tooolbox** [comment]
@isaacs Interesting.  Never heard of this streaming stuff before, but I skimmed a blog post on it.

``` bash
$ node --version
v0.10.38
```

Still not sure what my 0.10.x version means, but fine :)  

I figured I'd try your commit out.  Added a config.json:

``` json
{
    "dependencies": {
        "tap": "https://github.com/isaacs/node-tap.git#89ae5e672e4619cfad9bebd11225feefdf85fdde"
    }
}
```

``` bash
$ npm update
tap@1.3.4 node_modules/tap
├── supports-color@1.3.1
├── opener@1.4.1
├── deep-equal@1.0.1
├── only-shallow@1.2.0
├── deeper@2.1.0
├── foreground-child@1.3.0
├── signal-exit@2.1.2
├── readable-stream@2.0.2 (process-nextick-args@1.0.2, inherits@2.0.1, isarray@0.0.1, util-deprecate@1.0.1, string_decoder@0.10.31, core-util-is@1.0.1)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── tap-parser@1.1.6 (inherits@2.0.1, events-to-array@1.0.2, readable-stream@1.1.13)
├── glob@5.0.14 (path-is-absolute@1.0.0, inherits@2.0.1, inflight@1.0.4, once@1.3.2, minimatch@2.0.10)
├── coveralls@2.11.4 (lcov-parse@0.0.6, log-driver@1.2.4, request@2.40.0, js-yaml@3.0.1)
├── tap-mocha-reporter@0.0.17 (escape-string-regexp@1.0.3, diff@1.4.0, debug@2.2.0, readable-stream@1.1.13, unicode-length@1.0.0)
├── js-yaml@3.4.0 (esprima@2.2.0, argparse@1.0.2)
└── nyc@3.1.0 (rimraf@2.4.3, spawn-wrap@1.0.1, strip-bom@2.0.0, yargs@3.23.0, lodash@3.10.1, istanbul@0.3.19)
```

(Same code as my last post.)

``` bash
$ node test_tap.js
TAP version 13
    # Subtest: the whole script
Initial content:

Ana
Benjamin
Frank

        # Subtest: the file when we start
        ok 1 - should have content
        1..1
    ok 1 - the file when we start # time=5.527ms

Adding Lara...
        # Subtest: the file when we end
        ok 1 - should now have Lara's name
        1..1
    ok 2 - the file when we end # time=9.668ms

Adding Joe...
        # Subtest: the file when we end
        not ok 1 - should now have Bob's name
          ---
          at:
            file: test_tap.js
            line: 35
            column: 32
          showDiff: false
          actual: |
            Ana
            Benjamin
            Frank
            Lara
            Joe
          expected: null
          message: "AssertionError: expected 'Ana\\nBenjamin\\nFrank\\nLara\\nJoe\\n' to include 'Bob'"
          source: |
            fileContent.should.contain('Bob');
          stack: |
            test_tap.js:35:32
            Test.<anonymous> (node_modules/tap/lib/assert.js:235:7)
            Test.ASSERT [as _currentAssert] (node_modules/tap/lib/test.js:1074:15)
            it (node_modules/tap/lib/mocha.js:28:7)
            test_tap.js:34:9
            node_modules/tap/lib/mocha.js:45:7
            Test.test (node_modules/tap/lib/test.js:398:27)
            describe (node_modules/tap/lib/mocha.js:44:7)
            test_tap.js:33:5
          ...
        Bail out! # should now have Bob's name
Bail out! # should now have Bob's name
Adding Bob...
Writing file...
Done!
```

So, the output is in the logical sequence now, and the report was delivered when expected, but it did run the rest of the content in the outer `describe()`.  I feel like that's not intended?

At this point I feel a little nitpicky, but if my tests and feedback are helpful, we can keep rolling :)

**Comment by isaacs** [comment]
> At this point I feel a little nitpicky, but if my tests and feedback are helpful, we can keep rolling :)

No worries, it's fine :)

So, the behavior proposed in #167 would be like adding this to your code:

```
tap.on('bailout', function () {
  process.exit(1)
})
```

which would do what yo'ure asking for.

**Comment by tooolbox** [comment]
Hey, neato!  Yes, adding that does work perfectly now.  I removed the outer `describe()` and it behaves just fine.  So this:

``` js
var fs = require('fs');
var should = require('chai').should();
var tap = require('tap');

tap.mochaGlobals();
tap._bail = true;
tap.on('bailout', function(){
    process.exit(1);
});

var fileContent = fs.readFileSync('./names.txt', 'utf8');
console.log('Initial content:\n');
console.log(fileContent);
describe('the file when we start', function(){
    it('should have content', function(){
        fileContent.should.equal('Ana\nBenjamin\nFrank\n');
    });
});

// process the file in some way
console.log('Adding Lara...');
fileContent += 'Lara\n'

describe('the file when we end', function(){
    it("should now have Lara's name", function(){
        fileContent.should.contain('Lara');
    });
});

console.log('Adding Joe...');
fileContent += 'Joe\n';

// Failing test!
describe('the file when we end', function(){
    it("should now have Bob's name", function(){
        fileContent.should.contain('Bob');
    });
});

console.log('Adding Bob...');
fileContent += 'Bob\n';

describe('the file when we end', function(){
    it("should now have Bob's name", function(){
        fileContent.should.contain('Bob');
    });
});

console.log('Writing file...');
fs.writeFileSync('./changedFile.txt', fileContent);

console.log('Done!');
```

Behaves exactly as desired.  Thanks very much for your help!

**Comment by isaacs** [comment]
Ok, cool!  I'll publish the updated readable-stream dep tomorrow.

In the meantime, I'd like to think a bit more about whether it makes sense to have bailouts result in immediate forceful process exit.  That has some more ramifications.

**Comment by tooolbox** [comment]
If it's worth anything, I feel that my use case is odd enough that I wouldn't necessarily expect it to be the default behavior.  I looked through three or four testing frameworks, trying to find one modular enough to be used in-line with my processing scripts, before I came upon Tap.  I'm more than satisfied with the ability to turn on the bailout flag and attach an event handler! :+1: 

If you decide not to make it default because of other factors, I think a couple of documented flags would be sufficient for anyone else like me that comes along.  :)
