### ISSUE TITLE
Code coverage does not work with TypeScript

### ISSUE THREAD

**Issue by delvedor** [tapjs/tapjs#536]
Hello!
Not sure if I'm missing something or this is a bug, I'm trying to get the code coverage for a TypeScript project, but once I run the test command with `--cov --coverage-report=html`, the coverage is always empty.

Am I missing something?
I've created a small repository to reproduce the issue: [delvedor/tap-ts-coverage](https://github.com/delvedor/tap-ts-coverage)

Thanks!

**Comment by isaacs** [comment]
Hm.  It looks like the source map is confusing NYC somehow.  When I run `nyc node --require=ts-node/register node test/test.js`, it shows no coverage.  When I strip the source map comment from the `lib/index.js` file, and run nyc again, it shows 100% coverage.

cc: @coreyfarrell

**Comment by isaacs** [comment]
Found the issue with @coreyfarrell's help.  NYC v14 requires that `--extension` be supplied in the NYC config for non-.js files.  Fixed in tap v12.6.4 b05fe31 and v13.0.0-rc.29 7ea20fc.

**Comment by isaacs** [comment]
er, make that 12.6.5 9eb9738 and 13.0.0-rc.30 4f2ff50, due to an unfortunate typo.

**Comment by delvedor** [comment]
Hello!
I've updated `tap` to `v12.6.5`, but it's still not working. Am I missing something?
I've updated the test repo as well.

**Comment by coreyfarrell** [comment]
@isaacs looks like you're not passing the `--extension` option to `nyc report` or `nyc check-coverage`.  You might even want to pass `options.nycArgs` to these commands as well, especially if that array might have `--include` or `--exclude` options from tap users.

https://github.com/tapjs/node-tap/blob/9eb97387fcc403eb6704baa64f401efd2d43bbfc/bin/run.js#L528
https://github.com/tapjs/node-tap/blob/9eb97387fcc403eb6704baa64f401efd2d43bbfc/bin/run.js#L566

**Comment by delvedor** [comment]
Using `v13.0.1` appears to solve the issue.

**Comment by isaacs** [comment]
@delvedor I also pushed a new v12 on the `tap@legacy` dist-tag that fixes this issue.  But keep using v13, it's the new hotness :)

**Comment by delvedor** [comment]
I'm already using v13 in all the projects that support Node ≥ v8, hopefully soon I'll migrate everything else.

Thank you for all the amazing work!
