### ISSUE TITLE
Disable coverage report on watch runs

### ISSUE THREAD

**Issue by jsumners** [tapjs/tapjs#553]
`tap -n -w --no-coverage-report test/foo.test.js` will result in the ASCII coverage report being displayed after every run. This makes it difficult to see the actual result of the test passes/failures.

**Comment by isaacs** [comment]
Huh.  Looks like that was never actually implemented.

Landed on 13.1.6.  You can also use `--nyc-arg=--silent`, but obviously that's a bit more into the implementation details.

**Comment by jsumners** [comment]
Awesome. Thank you.

**Comment by jsumners** [comment]
FYI: the coverage report still shows when running the command in my original comment. Tested on 13.1.8.

**Comment by isaacs** [comment]
My bad.  I was misunderstanding my own code, common problem.

Should be actually fixed now on 13.1.9.

**Comment by jsumners** [comment]
Hooray! It's working as desired now. Thank you.

**Comment by reergymerej** [comment]
I'm still seeing this.  I'm just learning tap, so it's possible I'm screwing something up.  If so, maybe I could help document this.

sscce: https://github.com/reergymerej/wtf-coverage

**Comment by reergymerej** [comment]
From what I can tell, nyc intentionally ignores the `--silent` flag if it was passed to later.
https://github.com/istanbuljs/nyc/pull/322

![Screen Shot 2019-05-23 at 11 39 56 AM](https://user-images.githubusercontent.com/1720010/58277866-922fb800-7d4f-11e9-82c4-e6dbdc5e8cb3.png)


`nyc --silent bling blang bloo` mutes the report.
`nyc bling blang bloo --silent` does not.

https://github.com/tapjs/node-tap/blob/6db1cb38e5dea998ea80f0e2e5e2cdcb2489d690/bin/run.js#L245-L264
The `--silent` option (via `...reporter`) isn't included until after the report command.  Is this the problem?  Am I crazy?

**Comment by reergymerej** [comment]
Looks like the `report` option overrides the `--silent` flag anyway, so there may be multiple problems here.

![Screen Shot 2019-05-23 at 12 05 24 PM](https://user-images.githubusercontent.com/1720010/58279410-349d6a80-7d53-11e9-8854-f6ea6e91bd80.png)

**Comment by isaacs** [comment]
It's a regression for a different reason.  Pushing a fix now.

**Comment by reergymerej** [comment]
perfecto
